name: consultsphere
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #state management
  flutter_bloc: ^8.1.3

  #powerful HTTP networking
  dio: ^5.4.0

  #Secure Storage
  flutter_secure_storage: ^9.0.0

  #Shared Preferences
  shared_preferences: ^2.2.2

  #internet_connection_checker
  internet_connection_checker: ^1.0.0+1

  #declarative routing package
  go_router: ^13.1.0

  #Screenutil
  flutter_screenutil: ^5.9.0

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.7

  #dateFormat
  intl: ^0.19.0

  #Permission Handler
  permission_handler: ^11.2.0

  #Email Validator
  email_validator: ^2.1.17

  #Flutter Toast
  fluttertoast: ^8.2.4

  #SMS Auto Fill
  sms_autofill: ^2.3.0

  #Read More Article
  readmore: ^2.2.0

  #device_info_plus
  device_info_plus: ^9.1.2

  #Flutter Svg
  flutter_svg: ^2.0.9

  #Page Transition
  page_transition: ^2.1.0

  #Intl_phone_number_input
  intl_phone_number_input: ^0.7.4

  #Persistent Bottom Nav Bar
  persistent_bottom_nav_bar: ^5.0.2

  #cached image
  cached_network_image: ^3.3.1

  #Pinput
  pinput: ^3.0.1

  #Carousel Slider
  carousel_slider: ^4.2.1

  #Firebase core
  firebase_core: ^2.25.4

  #Firebase auth
  firebase_auth: ^4.17.4

  #Google sign in
  google_sign_in: ^6.2.1

  #Facebook Auth
  flutter_facebook_auth: ^6.0.4

  #Apple sign in
  sign_in_with_apple: ^5.0.0

  #Firebase firestore
  cloud_firestore: ^4.15.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  flutter_gen: ^5.4.0

  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/core/utils/gen/
  line_length: 1000 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/playstore.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/RalewayRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewaySemiBold.ttf
          weight: 600
        - asset: assets/fonts/RalewayRegular.ttf
          weight: 400
        - asset: assets/fonts/RalewayRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewayRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RalewayRomanSemiBold.ttf
          weight: 600
    - family: Inter
      fonts:
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterBlackItalic.ttf
          weight: 900
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
