// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGLAoKQ_e8GTqIZlMqUOWvP4muCkhdjjc',
    appId: '1:287860088737:android:72c32025fabf64a4ef75e0',
    messagingSenderId: '287860088737',
    projectId: 'consultsphere-2400f',
    storageBucket: 'consultsphere-2400f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCDeKIH8lpCUUR2tKpZDz7sGzneBl7z5s',
    appId: '1:287860088737:ios:22347eb7e75d682aef75e0',
    messagingSenderId: '287860088737',
    projectId: 'consultsphere-2400f',
    storageBucket: 'consultsphere-2400f.appspot.com',
    androidClientId: '287860088737-2h2l1m3cr75588vntdp86jpufsfqjs5g.apps.googleusercontent.com',
    iosClientId: '287860088737-ca2sv6f5nnac33hqmha8r6tslv72otei.apps.googleusercontent.com',
    iosBundleId: 'com.example.consultsphere',
  );
}
